### ISSUE TITLE
BUG: UploadFileOnReference of for Community guidelines fails for old (existing) spaces data

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3763]
**Describe the bug**

**To Reproduce**
1. Go to https://dev-alkem.io/admin/spaces/space-mig/community
2. Try to upload file to Community guidelines reference - error is thrown
<img width="1631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aad215dcc609f665f5313bf8b1e55d99fa9fcc55/image.png" alt="image.png" />

**Expected behavior**
File upload is successful on old and new spaces community guideline.

**Comment by techsmyth** [comment]
@Comoque1  think this is fixed by 3740

**Comment by Comoque1** [comment]
@techsmyth ok, I will test it with ones the other is merged.

**Comment by Comoque1** [comment]
The issue is still reproducible and the error is different:
<img width="1317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d220e0c62f460d2d558d3897b1114206c3410974/image.png" alt="image.png" />

**Comment by hero101** [comment]
I have used a backup of acceptance.
It turns out that the `allowedMimeTypes` and/or `maxFileSize` are `NULL`. Setting the default values for the columns fixes the problem. @valentinyanakiev thoughts on next steps?
